import type { DomainData } from "@/app/Orrery";

export const DEMO_DOMAINS: DomainData[] = [
  {
    id: "demo-1",
    name: "Health",
    slug: "health",
    status: "ALIGNED",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0.18,
    color: "#ff00fd",
    autoDrifted: false,
  },
  {
    id: "demo-2",
    name: "Career",
    slug: "career",
    status: "ALIGNED",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0.82,
    color: null,
    autoDrifted: false,
  },
  {
    id: "demo-3",
    name: "Relationships",
    slug: "relationships",
    status: "ARCHIVED",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0.88,
    color: "#ed720c",
    autoDrifted: false,
  },
  {
    id: "demo-4",
    name: "YouTube",
    slug: "youtube",
    status: "NEUTRAL",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0,
    color: null,
    autoDrifted: false,
  },
  {
    id: "demo-5",
    name: "X",
    slug: "x",
    status: "NEUTRAL",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0.696,
    color: null,
    autoDrifted: false,
  },
  {
    id: "demo-6",
    name: "Instagram",
    slug: "instagram",
    status: "NEUTRAL",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0,
    color: null,
    autoDrifted: false,
  },
  {
    id: "demo-7",
    name: "Lush",
    slug: "lush",
    status: "ALIGNED",
    identity: null,
    nextMove: null,
    primaryReason: null,
    positionX: 0.434,
    color: null,
    autoDrifted: false,
  },
];
