import type { DomainData } from "@/app/Orrery";

/**
 * A bundled, read-only fallback for the public orrery. Production normally
 * loads the curated demo through Supabase, but this keeps the first impression
 * available during a transient database or RPC failure.
 */
export const DEMO_DOMAINS: DomainData[] = [
  {
    id: "demo-health",
    name: "Health",
    slug: "health",
    status: "DRIFTING",
    identity: "I protect the energy that everything else depends on.",
    nextMove: "Train for 30 minutes.",
    primaryReason: "Energy makes every other domain easier to sustain.",
    positionX: 0.82,
    color: "#f87171",
    autoDrifted: true,
  },
  {
    id: "demo-career",
    name: "Career",
    slug: "career",
    status: "ALIGNED",
    identity: "I build useful things and finish them well.",
    nextMove: "Ship the next product milestone.",
    primaryReason: "Craft compounds when the work keeps moving.",
    positionX: 0.68,
    color: "#67e8f9",
    autoDrifted: false,
  },
  {
    id: "demo-relationships",
    name: "Relationships",
    slug: "relationships",
    status: "ALIGNED",
    identity: "I show up with attention and consistency.",
    nextMove: "Call someone I care about.",
    primaryReason: "Strong relationships require active presence.",
    positionX: 0.36,
    color: "#67e8f9",
    autoDrifted: false,
  },
  {
    id: "demo-business",
    name: "Business",
    slug: "business",
    status: "NEUTRAL",
    identity: "I turn useful ideas into durable systems.",
    nextMove: "Talk to one customer.",
    primaryReason: "Reality is clearer after contact with users.",
    positionX: 0.24,
    color: "#67e8f9",
    autoDrifted: false,
  },
  {
    id: "demo-school",
    name: "School",
    slug: "school",
    status: "ALIGNED",
    identity: "I learn deeply and finish what I start.",
    nextMove: "Complete the next focused study block.",
    primaryReason: "Deliberate practice creates leverage.",
    positionX: 0.48,
    color: "#67e8f9",
    autoDrifted: false,
  },
  {
    id: "demo-internships",
    name: "Internships",
    slug: "internships",
    status: "DRIFTING",
    identity: "I create opportunities through consistent outreach.",
    nextMove: "Send one thoughtful application.",
    primaryReason: "Momentum comes from steady, targeted action.",
    positionX: 0.78,
    color: "#f87171",
    autoDrifted: true,
  },
  {
    id: "demo-tennis",
    name: "Tennis",
    slug: "tennis",
    status: "NEUTRAL",
    identity: "I practice with intent.",
    nextMove: "Schedule the next court session.",
    primaryReason: "Skill stays alive through repetition.",
    positionX: 0.58,
    color: "#67e8f9",
    autoDrifted: false,
  },
  {
    id: "demo-reading",
    name: "Reading",
    slug: "reading",
    status: "ALIGNED",
    identity: "I make space for ideas that change how I think.",
    nextMove: "Read for 20 minutes.",
    primaryReason: "A small daily practice keeps learning continuous.",
    positionX: 0.3,
    color: "#67e8f9",
    autoDrifted: false,
  },
  {
    id: "demo-kick-boxing",
    name: "Kick Boxing",
    slug: "kick-boxing",
    status: "ARCHIVED",
    identity: "I can pause a domain without losing it.",
    nextMove: null,
    primaryReason: "Archived domains remain visible without demanding attention.",
    positionX: null,
    color: "#71717a",
    autoDrifted: false,
  },
  {
    id: "demo-content",
    name: "Content Creation",
    slug: "content-creation",
    status: "ARCHIVED",
    identity: "I publish when the work has something useful to say.",
    nextMove: null,
    primaryReason: "Not every domain needs to be active at the same time.",
    positionX: null,
    color: "#71717a",
    autoDrifted: false,
  },
];
